Create local environment template
wpaustralia/wpaustralia.org pull request #16
Opened 2018-03-23 07:57 UTC by BronsonQuick

Fixes #15

2018-03-23 09:09 UTC, ntwb commented on CNAME
> -wpaustralia.org
This file needs to remain until we have a host hosting setup for https://wpaustralia.org

2018-03-23 09:09 UTC, ntwb commented on README.md
> +2. Change directories into the a folder where you would like to download the project. e.g. `cd /Volumes/Sites`
`... directories into the folder`, rather than `... directories into the a folder` please

2018-03-23 09:09 UTC, ntwb commented on README.md
> +* [Mailhog](https://github.com/Chassis/mailhog) - This extension setup Mailhog which catches all the email WordPress sends. You can see the dashboard for it by visiting. [http://wpaustralia.org:8025/
`http://wpaustralia.local:8025/` rather than `http://wpaustralia.org:8025/` please

2018-03-23 09:09 UTC, ntwb commented on README.md
> +* `vagrant up` - Run this in the directory you installed this project in to boot up your development environment. e.g. `cd /Volumes/Sites/wpaustralia; vagrant up` then browse to [http://wpaustralia.l
"Run this from the `wpaustralia` directory where you downloaded and installed this project

2018-03-23 09:12 UTC, ntwb requested changes
As per my comment on the `CNAME` file deletion, we can't delete any of these files until we have DNS pointed at out new host (which at the time of writing we do not currently have)

2018-03-23 09:12 UTC, ntwb commented on README.md
> +If you're new to give them here are a few steps to help you get started:
???

2018-03-26 01:58 UTC, BronsonQuick commented
@ntwb Thanks for the review. Sorry for lots of horrible English as I was rushing and didn't proofread anything 🤣

I've added a new branch called `development` and changed this PR to merge into that. That way we can keep the CNAME stuff for Github in `master` and work on adding themes and plugins in development then when we're ready to switch to a WordPress install on the site we can merge development into master and alter the workflow.

2018-03-26 05:47 UTC, ntwb commented
Thanks a bunch for the PR and follow up 💐

2018-03-26 05:47 UTC, ntwb approved these changes
LGTM (Looks Good To Me) 👍

2018-03-26 05:48 UTC, merged