Brand new design
wpaustralia/wpaustralia.org pull request #2
Opened 2017-02-22 23:46 UTC by lukecarbis

2017-02-22 23:52 UTC, ntwb requested changes
LGTM @lukecarbis, I've just one issue, we need to keep the CNAME domain name alias file.

2017-02-22 23:52 UTC, ntwb commented on CNAME
> -wpaustralia.org
We need to keep this so we can continue to host this site at wpaustralia.org

2017-02-23 00:52 UTC, lukecarbis commented
Whoops! Done.

2017-02-23 01:06 UTC, merged

2017-02-23 02:00 UTC, ntwb commented
Thanks a bunch Luke 💐

2017-02-23 02:00 UTC, lukecarbis commented
You're welcome.
> On 23 Feb 2017, at 12:00, Stephen Edgar <notifications@github.com> wrote:
> 
> Thanks a bunch Luke 💐
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/wpaustralia/wpaustralia.org/pull/2#issuecomment-281867518>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ABC_wyJ8E6wn5ESRw5KypQcm-sDtLXd8ks5rfOgsgaJpZM4MJWWJ>.
>